require("dotenv").config();

const nextConfig = {
  env: {
    // backend api
    BACKEND_API: process.env.BACKEND_API,

    // test api
    BACKEND_API_DROP_CURRENT_DATE_API:
      process.env.BACKEND_API_DROP_CURRENT_DATE_API,

    // consumer_transaction api
    BACKEND_API_CONSUMER_TRANSACT: process.env.BACKEND_API_CONSUMER_TRANSACT,

    BACKEND_API_CONSUMER_TRANSACT_NOW_SERVE_PAY:
      process.env.BACKEND_API_CONSUMER_TRANSACT_NOW_SERVE_PAY,
    BACKEND_API_CONSUMER_TRANSACT_NOW_SERVE_CW:
      process.env.BACKEND_API_CONSUMER_TRANSACT_NOW_SERVE_CW,

    BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_PAY:
      process.env.BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_PAY,
    BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_CW:
      process.env.BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_CW,

    BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_CW_LATEST:
      process.env.BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_CW_LATEST,
    BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_PAY_LATEST:
      process.env.BACKEND_API_CONSUMER_TRANSACT_IN_QUEUE_PAY_LATEST,

    BACKEND_API_CONSUMER_TRANSACT_COMPLETE:
      process.env.BACKEND_API_CONSUMER_TRANSACT_COMPLETE,

    BACKEND_API_CONSUMER_TRANSACT_STATUS:
      process.env.BACKEND_API_CONSUMER_TRANSACT_STATUS,

    BACKEND_API_CONSUMER_TRANSACT_SELECT_DATE:
      process.env.BACKEND_API_CONSUMER_TRANSACT_SELECT_DATE,

    BACKEND_API_CONSUMER_TRANSACT_TRANSFER:
      process.env.BACKEND_API_CONSUMER_TRANSACT_TRANSFER,

    // transaction_type api
    BACKEND_API_TRANSACT_TYPE: process.env.BACKEND_API_TRANSACT_TYPE,

    // consumer_priority api
    BACKEND_API_CONSUMER_PRIO: process.env.BACKEND_API_CONSUMER_PRIO,

    // counter_personnel api
    BACKEND_API_COUNTER_PERSONNEL: process.env.BACKEND_API_COUNTER_PERSONNEL,

    // sub_transaction_type api
    BACKEND_API_SUB_TRANSACT_TYPE: process.env.BACKEND_API_SUB_TRANSACT_TYPE,
    BACKEND_API_SUB_TRANSACT_TRANSACT_TYPE:
      process.env.BACKEND_API_SUB_TRANSACT_TRANSACT_TYPE,

    // transaction_status api
    BACKEND_API_TRANSACT_STATUS: process.env.BACKEND_API_TRANSACT_STATUS,

    // transaction_type api
    BACKEND_API_TRANSACT_TYPE: process.env.BACKEND_API_TRANSACT_TYPE,

    // transferred_consumer api
    BACKEND_API_TRANSFERRED_CONSUMER:
      process.env.BACKEND_API_TRANSFERRED_CONSUMER,

    // transferred_consumer_from api
    BACKEND_API_TRANSFERRED_CONSUMER_FROM:
      process.env.BACKEND_API_TRANSFERRED_CONSUMER_FROM,
    BACKEND_API_TRANSFERRED_CONSUMER_TRANSFER_FROM:
      process.env.BACKEND_API_TRANSFERRED_CONSUMER_TRANSFER_FROM,

    // transferred_consumer_to api
    BACKEND_API_TRANSFERRED_CONSUMER_TO:
      process.env.BACKEND_API_TRANSFERRED_CONSUMER_TO,

    // auth
    BACKEND_API_AUTH: process.env.BACKEND_API_AUTH,
    BACKEND_API_AUTH_LOGIN: process.env.BACKEND_API_AUTH_LOGIN,
    BACKEND_API_AUTH_PROFILE: process.env.BACKEND_API_AUTH_PROFILE,
  },
  reactStrictMode: true,
};

module.exports = nextConfig;